# Generated by Django 5.1.7 on 2025-04-03 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_table'),
        ('users', '0002_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='nickname',
            field=models.CharField(default='내 계좌', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', default='bf7dfc9e-6e59-46e8-9ef4-efaabb2fe51b', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
