name: bank-project

services:
  backend:
    build: ./backend
    container_name: django_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    container_name: vanilla_frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html   # 개발 중에만 사용
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend # 순서만 보장

# 로컬에서 개발용 DB 컨테이너 생성
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 5s
      timeout: 3s
      retries: 5

  zap:
    build: ./analysis/zap
    container_name: zap_scanner
    ports:
      - "8090:8090"
    volumes:
      - ./analysis/zap:/zap/wrk  # 명세(schema.json) 파일 저장용
    depends_on:
      backend:
        condition: service_healthy
        
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel_collector
    command: ["--config=/etc/otelcol-contrib/otel-collector-config.yaml"]
    volumes:
      - ./backend/telemetry/config:/etc/otelcol-contrib
    ports:
      - "1888:1888"    # pprof extension
      - "9999:8888"    # Prometheus metrics exposed by the Collector
      - "13133:13133"  # health_check extension
      - "4317:4317"    # OTLP gRPC receiver
      - "4318:4318"    # OTLP HTTP receiver
      - "55679:55679"  # zPages extension
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./backend/telemetry/config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector

volumes:
  mysql_data:
