# Generated by Django 5.1.7 on 2025-04-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='sender_account',
            new_name='from_account',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='message',
            new_name='memo',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='receiver_account',
            new_name='to_account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance_after',
            field=models.IntegerField(default=0),
        ),
    ]
